server:
  port: 8080

spring:
  application:
    name: gyxmb-qywx
  profiles:
    active: dev


# 日志级别
logging:
  level:
    com.yss.shopping: debug


# mybtais-plus
mybatis-plus:
  mapper-locations: classpath*:mapper/**/*Mapper.xml




